var langEn = {
	'myRoom': 'You are in a small room but it have a table with some books and a chair, a window with a long blue curtain and a bedside table next to bed with a bedside clock. In front of you, a door.',
	'corridor': 'You are in a corridor with a big door called "EXIT".',
	'iCant': 'I can not understand you.',
	'me': 'You are in your house and you want to go play outside with your friends.',
	'say': 'Say... what?',
		'sayJohn': '... Your buddy John looks at window and see you. He smiles and salute you. You think that John did not understand you.',
		'sayNothing': '... Nothing happend.',
	'go': 'To... where?',
		'goTable': 'You have come to the table.<br>The table has a Math book open in the page 34 (geometry) and a notebook with exercises. The notebook has a note (strange right?).',
		'goBed': 'You have come to the bed.<br>Is a big bed, very confortable, but you do not have sleep.',
		'goDoor': 'You move to your room door.',
		'goExit': 'You move to the exit door.',
		'goWindow': 'You move to the window and you can see your friends playing at street. You wish go with them.',
		'goNoWhere': 'Impossible to move.',
	'open': 'Open... what?',
		'openDoorRoom': 'Door opened. You are again in your room.',
		'openDoorCorridor': 'Door opened.',
		'openWindow': 'It is closed.',
		'forget': 'You forget... something.',
		'finish': 'You go out with your friends to play.<br>CONGRATULATIONS!',
		'openNothing': 'Impossible to open.',
	'do': 'Do... what?',
		'doHomework': 'You sit in the chair and take your pencil and start your homework. After 10 minutes you finish.',
		'doFinish': 'You have done your homework.',
		'doNothing': 'You can not do that.',
	'read': 'Read... what?',
		'readNote': '"Please honey, finish your homework before you go play with your friends.<br>Love you,<br>Mom"',
		'readNothing': 'Impossible to read.',
	'won': 'You have won... what do you want more???'
};